plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.hyliankid14.bbcradioplayer.androidautobridge'
version = '0.1.0'

android {
  namespace "com.hyliankid14.bbcradioplayer.androidautobridge"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.core:core:1.13.1'
  implementation 'androidx.media:media:1.7.0'
  implementation 'androidx.media3:media3-exoplayer:1.4.1'
  implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
  implementation 'androidx.media3:media3-datasource:1.4.1'
}
