const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Makes debug builds report the next patch version, so a sideloaded debug APK can always be told
 * apart from the release it was built on top of (release 2.0.0 -> debug 2.0.1).
 *
 * `react-app/android` is regenerated by `npx expo prebuild`, so the change lives here rather than
 * in the generated Gradle files. Only the debug variants are touched: `androidComponents.onVariants`
 * overrides the output version name/code and leaves the release (GitHub and Play) variants on the
 * app.json version. The JavaScript side reads the same bump from `EXPO_PUBLIC_BUILD_VARIANT=debug`
 * (see react-app/src/config/buildInfo.ts).
 *
 * A tag `vX.Y.Z` must still match `expo.version`; this plugin never rewrites app.json.
 */

const MARKER = "// ── withAndroidDebugVersion ──";

/** Returns `version` with its patch incremented, or null when it is not a plain `major.minor.patch`. */
function bumpPatch(version) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(version ?? "").trim());
  if (!match) return null;
  return `${match[1]}.${match[2]}.${Number(match[3]) + 1}`;
}

module.exports = function withAndroidDebugVersion(config) {
  const releaseVersion = config.version;
  const debugVersionName = bumpPatch(releaseVersion);
  if (!debugVersionName) {
    // Not a plain semver version; leave the project untouched rather than guess.
    return config;
  }

  const baseVersionCode = config.android?.versionCode;
  const outputLines = [
    `            output.versionName.set("${debugVersionName}")`
  ];
  if (typeof baseVersionCode === "number") {
    outputLines.push(`            output.versionCode.set(${baseVersionCode + 1})`);
  }

  const gradleBlock = `
${MARKER}
// Appended by react-app/plugins/withAndroidDebugVersion.js. Debug builds report the next patch
// version ("${releaseVersion}" -> "${debugVersionName}") so a sideload is distinguishable from the
// release build. Do not edit android/app/build.gradle — android/ is regenerated by "expo prebuild".
androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.outputs.each { output ->
${outputLines.join("\n")}
        }
    }
}
`;

  return withAppBuildGradle(config, (configWithBuildGradle) => {
    if (!configWithBuildGradle.modResults.contents.includes(MARKER)) {
      configWithBuildGradle.modResults.contents += gradleBlock;
    }
    return configWithBuildGradle;
  });
};
