const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Adds the GitHub / Play distribution channels to the generated Android project.
 *
 * `react-app/android` is regenerated by `npx expo prebuild`, so every change that must survive a
 * prebuild lives here rather than in the generated Gradle files.  The generated project ships a
 * single `release` build type signed with the debug keystore; this plugin appends a second
 * `android { }` block (the Groovy DSL merges every `android { }` block into the same extension)
 * that adds:
 *
 *   - a `distribution` flavour dimension with `github` and `play` flavours, so the release tasks
 *     are `:app:assembleGithubRelease` and `:app:bundlePlayRelease`
 *   - a `githubShared` signing config — the repository debug keystore that
 *     `withAndroidCleartextTraffic` copies into `app/debug.keystore` — used by GitHub releases so
 *     sideloaded builds keep upgrading in place
 *   - a `release` signing config resolved from `-PRELEASE_*` properties, `RELEASE_*`
 *     environment variables or `~/.gradle/gradle.properties` (the same precedence the legacy
 *     Kotlin modules use) and used by the `play` flavour
 *   - an `.debug` application id suffix so debug sideloads can never collide with the
 *     Play/GitHub-signed app
 *
 * The `play` flavour refuses to build when no real release key is available: Play would reject a
 * bundle signed with the debug keystore, and signing GitHub releases with the release key would
 * break sideload upgrade-in-place.
 */

const CHANNEL_ENV_VAR = "EXPO_PUBLIC_DISTRIBUTION_CHANNEL";
const MARKER = "// ── withAndroidReleaseChannels ──";

const GRADLE_BLOCK = `
${MARKER}
// Everything below is appended by react-app/plugins/withAndroidReleaseChannels.js.
// Do not edit it in android/app/build.gradle — android/ is regenerated by "expo prebuild".

def releaseStoreFile = resolveSigningProperty("RELEASE_STORE_FILE")
def releaseStorePassword = resolveSigningProperty("RELEASE_STORE_PASSWORD")
def releaseKeyAlias = resolveSigningProperty("RELEASE_KEY_ALIAS")
def releaseKeyPassword = resolveSigningProperty("RELEASE_KEY_PASSWORD")
def hasReleaseSigning = !!(releaseStoreFile && releaseStorePassword && releaseKeyAlias && releaseKeyPassword)

// The distribution channel the JavaScript bundle is built for.  It is inlined from
// ${CHANNEL_ENV_VAR} at bundle time, so it also selects the release signing config below.
def distributionChannel = (System.getenv("${CHANNEL_ENV_VAR}") ?: "github").trim()

android {
    flavorDimensions += ["distribution"]

    signingConfigs {
        // GitHub release builds share the repository debug keystore so that sideloaded APKs can
        // always upgrade in place across machines and CI builds.
        githubShared {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        // Google Play builds use the Play upload key.  Never falls back to the debug keystore:
        // the play flavour is blocked at configuration time when this is unresolved.
        release {
            if (hasReleaseSigning) {
                storeFile file(releaseStoreFile)
                storePassword releaseStorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    productFlavors {
        github {
            dimension "distribution"
            signingConfig signingConfigs.githubShared
        }
        play {
            dimension "distribution"
            signingConfig signingConfigs.release
        }
    }

    buildTypes {
        debug {
            // Keep debug builds on their own application id so a debug sideload can be installed
            // alongside the release app, which is signed with a different key on Play.
            applicationIdSuffix ".debug"
        }
        release {
            // Default for a bare "assembleRelease"; the flavours above take precedence.
            signingConfig signingConfigs.githubShared
        }
    }
}

// The JS bundle is inlined from ${CHANNEL_ENV_VAR}, which Gradle does not otherwise treat as a
// task input.  Without this, building the play flavour after the github flavour in the same
// workspace can be reported UP-TO-DATE and silently ship the wrong bundle.
tasks.matching { it.name.contains("JsAndAssets") }.configureEach {
    inputs.property("distributionChannel", distributionChannel)
}

gradle.taskGraph.whenReady { graph ->
    // AGP registers \`pre<Variant>Build\` / \`post<Variant>Build\` lifecycle hooks for every flavour
    // in the project, so a github build also contains a task literally named prePlayReleaseBuild.
    // Only real play-release variant actions (assemblePlayRelease, bundlePlayRelease, …) count.
    def buildsPlayRelease = graph.allTasks.any { task ->
        if (task.project != project) return false
        def taskName = task.name
        if (taskName.startsWith("pre") || taskName.startsWith("post")) return false
        return taskName.contains("PlayRelease")
    }
    if (buildsPlayRelease && !hasReleaseSigning) {
        throw new GradleException(
            "Refusing to build the play flavour without a Google Play upload key.\\n" +
            "Set RELEASE_STORE_FILE, RELEASE_STORE_PASSWORD, RELEASE_KEY_ALIAS and " +
            "RELEASE_KEY_PASSWORD as gradle properties, environment variables, or in " +
            "~/.gradle/gradle.properties."
        )
    }
}
`;

const SIGNING_RESOLVER = `
/** Resolves a release signing value: -P gradle property, then env var, then the Gradle user home. */
def resolveSigningProperty(String key) {
    if (project.hasProperty(key)) {
        def fromProperty = project.property(key)?.toString()?.trim()
        if (fromProperty) return fromProperty
    }
    def fromEnv = System.getenv(key)?.trim()
    if (fromEnv) return fromEnv
    def userProperties = new Properties()
    def userPropertiesFile = new File(gradle.gradleUserHomeDir, "gradle.properties")
    if (userPropertiesFile.exists()) {
        userPropertiesFile.withInputStream { userProperties.load(it) }
    }
    def fromUserGradle = userProperties.getProperty(key)?.trim()
    return fromUserGradle ?: null
}
`;

function patchBuildGradle(contents) {
  if (contents.includes(MARKER)) return contents;
  return `${contents}\n${SIGNING_RESOLVER}${GRADLE_BLOCK}`;
}

module.exports = function withAndroidReleaseChannels(config) {
  return withAppBuildGradle(config, (configWithBuildGradle) => {
    configWithBuildGradle.modResults.contents = patchBuildGradle(
      configWithBuildGradle.modResults.contents
    );
    return configWithBuildGradle;
  });
};
