import Foundation

enum WatchStationCatalogue {
    
    static func allStations() -> [WatchStation] {
        return [
            // National
            WatchStation(id: "bbc_radio_one", title: "Radio 1", serviceId: "bbc_radio_one", streamServiceIds: ["bbc_radio_one"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_one/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_1xtra", title: "1Xtra", serviceId: "bbc_1xtra", streamServiceIds: ["bbc_1xtra"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_1xtra/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_one_dance", title: "Radio 1 Dance", serviceId: "bbc_radio_one_dance", streamServiceIds: ["bbc_radio_one_dance"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_one_dance/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_one_anthems", title: "Radio 1 Anthems", serviceId: "bbc_radio_one_anthems", streamServiceIds: ["bbc_radio_one_anthems"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_one_anthems/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_two", title: "Radio 2", serviceId: "bbc_radio_two", streamServiceIds: ["bbc_radio_two"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_two/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_three", title: "Radio 3", serviceId: "bbc_radio_three", streamServiceIds: ["bbc_radio_three"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_three/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_three_unwind", title: "Radio 3 Unwind", serviceId: "bbc_radio_three_unwind", streamServiceIds: ["bbc_radio_three_unwind"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_three_unwind/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_fourfm", title: "Radio 4", serviceId: "bbc_radio_fourfm", streamServiceIds: ["bbc_radio_fourfm"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_fourfm/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_four_extra", title: "Radio 4 Extra", serviceId: "bbc_radio_four_extra", streamServiceIds: ["bbc_radio_four_extra"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_four_extra/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_five_live", title: "5 Live", serviceId: "bbc_radio_five_live", streamServiceIds: ["bbc_radio_five_live"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_five_live/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_five_live_sports_extra", title: "5 Live Sports Extra", serviceId: "bbc_radio_five_live_sports_extra", streamServiceIds: ["bbc_radio_five_live_sports_extra"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_five_live_sports_extra/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_five_live_sports_extra_2", title: "5 Live Sports Extra 2", serviceId: "bbc_radio_five_live_sports_extra_2", streamServiceIds: ["bbc_radio_five_live_sports_extra_2"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_five_live_sports_extra_2/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_radio_five_live_sports_extra_3", title: "5 Live Sports Extra 3", serviceId: "bbc_radio_five_live_sports_extra_3", streamServiceIds: ["bbc_radio_five_live_sports_extra_3"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_five_live_sports_extra_3/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_6music", title: "6 Music", serviceId: "bbc_6music", streamServiceIds: ["bbc_6music"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_6music/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_6music_indie", title: "6 Music Indie Forever", serviceId: "bbc_6music_indie", streamServiceIds: ["bbc_6music_indie"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_6music_indie/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_asian_network", title: "Asian Network", serviceId: "bbc_asian_network", streamServiceIds: ["bbc_asian_network"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_asian_network/blocks-colour-black_600x600.png", category: .national),
            WatchStation(id: "bbc_world_service", title: "World Service", serviceId: "bbc_world_service", streamServiceIds: ["bbc_world_service"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_world_service/blocks-colour-black_600x600.png", category: .national),
            
            // Nations/Regions
            WatchStation(id: "bbc_radio_scotland_fm", title: "Radio Scotland", serviceId: "bbc_radio_scotland_fm", streamServiceIds: ["bbc_radio_scotland_fm"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_scotland_fm/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_scotland_mw", title: "Radio Scotland Extra", serviceId: "bbc_radio_scotland_mw", streamServiceIds: ["bbc_radio_scotland_mw"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_scotland_mw/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_wales_fm", title: "Radio Wales", serviceId: "bbc_radio_wales_fm", streamServiceIds: ["bbc_radio_wales_fm"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_wales_fm/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_wales_mw", title: "Radio Wales Extra", serviceId: "bbc_radio_wales_mw", streamServiceIds: ["bbc_radio_wales_mw"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_wales_mw/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_cymru", title: "Radio Cymru", serviceId: "bbc_radio_cymru", streamServiceIds: ["bbc_radio_cymru"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_cymru/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_cymru_2", title: "Radio Cymru 2", serviceId: "bbc_radio_cymru_2", streamServiceIds: ["bbc_radio_cymru_2"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_cymru_2/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_ulster", title: "Radio Ulster", serviceId: "bbc_radio_ulster", streamServiceIds: ["bbc_radio_ulster"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_ulster/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_foyle", title: "Radio Foyle", serviceId: "bbc_radio_foyle", streamServiceIds: ["bbc_radio_foyle"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_foyle/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_nan_gaidheal", title: "Radio nan Gàidheal", serviceId: "bbc_radio_nan_gaidheal", streamServiceIds: ["bbc_radio_nan_gaidheal"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_nan_gaidheal/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_orkney", title: "Radio Orkney", serviceId: "bbc_radio_orkney", streamServiceIds: ["bbc_radio_orkney"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_orkney/blocks-colour-black_600x600.png", category: .regions),
            WatchStation(id: "bbc_radio_shetland", title: "Radio Shetland", serviceId: "bbc_radio_shetland", streamServiceIds: ["bbc_radio_shetland"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_shetland/blocks-colour-black_600x600.png", category: .regions),
            
            // Local
            WatchStation(id: "bbc_radio_berkshire", title: "Radio Berkshire", serviceId: "bbc_radio_berkshire", streamServiceIds: ["bbc_radio_berkshire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_berkshire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_bristol", title: "Radio Bristol", serviceId: "bbc_radio_bristol", streamServiceIds: ["bbc_radio_bristol"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_bristol/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_cambridge", title: "Radio Cambridgeshire", serviceId: "bbc_radio_cambridge", streamServiceIds: ["bbc_radio_cambridge"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_cambridge/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_cornwall", title: "Radio Cornwall", serviceId: "bbc_radio_cornwall", streamServiceIds: ["bbc_radio_cornwall"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_cornwall/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_coventry_and_warwickshire", title: "Radio Coventry & Warwickshire", serviceId: "bbc_radio_coventry_and_warwickshire", streamServiceIds: ["bbc_radio_coventry_and_warwickshire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_coventry_and_warwickshire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_cumbria", title: "Radio Cumbria", serviceId: "bbc_radio_cumbria", streamServiceIds: ["bbc_radio_cumbria"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_cumbria/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_derby", title: "Radio Derby", serviceId: "bbc_radio_derby", streamServiceIds: ["bbc_radio_derby"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_derby/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_devon", title: "Radio Devon", serviceId: "bbc_radio_devon", streamServiceIds: ["bbc_radio_devon"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_devon/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_essex", title: "Radio Essex", serviceId: "bbc_radio_essex", streamServiceIds: ["bbc_radio_essex"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_essex/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_gloucestershire", title: "Radio Gloucestershire", serviceId: "bbc_radio_gloucestershire", streamServiceIds: ["bbc_radio_gloucestershire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_gloucestershire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_hereford_and_worcester", title: "Radio Hereford & Worcester", serviceId: "bbc_radio_hereford_and_worcester", streamServiceIds: ["bbc_radio_hereford_and_worcester"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_hereford_and_worcester/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_humberside", title: "Radio Humberside", serviceId: "bbc_radio_humberside", streamServiceIds: ["bbc_radio_humberside"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_humberside/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_kent", title: "Radio Kent", serviceId: "bbc_radio_kent", streamServiceIds: ["bbc_radio_kent"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_kent/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_leicester", title: "Radio Leicester", serviceId: "bbc_radio_leicester", streamServiceIds: ["bbc_radio_leicester"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_leicester/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_lincolnshire", title: "Radio Lincolnshire", serviceId: "bbc_radio_lincolnshire", streamServiceIds: ["bbc_radio_lincolnshire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_lincolnshire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_manchester", title: "Radio Manchester", serviceId: "bbc_radio_manchester", streamServiceIds: ["bbc_radio_manchester"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_manchester/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_merseyside", title: "Radio Merseyside", serviceId: "bbc_radio_merseyside", streamServiceIds: ["bbc_radio_merseyside"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_merseyside/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_norfolk", title: "Radio Norfolk", serviceId: "bbc_radio_norfolk", streamServiceIds: ["bbc_radio_norfolk"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_norfolk/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_northampton", title: "Radio Northampton", serviceId: "bbc_radio_northampton", streamServiceIds: ["bbc_radio_northampton"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_northampton/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_newcastle", title: "Radio Newcastle", serviceId: "bbc_radio_newcastle", streamServiceIds: ["bbc_radio_newcastle"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_newcastle/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_nottingham", title: "Radio Nottingham", serviceId: "bbc_radio_nottingham", streamServiceIds: ["bbc_radio_nottingham"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_nottingham/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_oxford", title: "Radio Oxford", serviceId: "bbc_radio_oxford", streamServiceIds: ["bbc_radio_oxford"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_oxford/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_sheffield", title: "Radio Sheffield", serviceId: "bbc_radio_sheffield", streamServiceIds: ["bbc_radio_sheffield"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_sheffield/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_shropshire", title: "Radio Shropshire", serviceId: "bbc_radio_shropshire", streamServiceIds: ["bbc_radio_shropshire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_shropshire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_solent", title: "Radio Solent", serviceId: "bbc_radio_solent", streamServiceIds: ["bbc_radio_solent"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_solent/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_somerset_sound", title: "Radio Somerset", serviceId: "bbc_radio_somerset_sound", streamServiceIds: ["bbc_radio_somerset_sound"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_somerset_sound/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_stoke", title: "Radio Stoke", serviceId: "bbc_radio_stoke", streamServiceIds: ["bbc_radio_stoke"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_stoke/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_suffolk", title: "Radio Suffolk", serviceId: "bbc_radio_suffolk", streamServiceIds: ["bbc_radio_suffolk"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_suffolk/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_surrey", title: "Radio Surrey", serviceId: "bbc_radio_surrey", streamServiceIds: ["bbc_radio_surrey"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_surrey/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_sussex", title: "Radio Sussex", serviceId: "bbc_radio_sussex", streamServiceIds: ["bbc_radio_sussex"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_sussex/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_tees", title: "Radio Tees", serviceId: "bbc_radio_tees", streamServiceIds: ["bbc_radio_tees"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_tees/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_three_counties_radio", title: "Three Counties Radio", serviceId: "bbc_three_counties_radio", streamServiceIds: ["bbc_three_counties_radio"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_three_counties_radio/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_wiltshire", title: "Radio Wiltshire", serviceId: "bbc_radio_wiltshire", streamServiceIds: ["bbc_radio_wiltshire"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_wiltshire/blocks-colour-black_600x600.png", category: .local),
            WatchStation(id: "bbc_radio_york", title: "Radio York", serviceId: "bbc_radio_york", streamServiceIds: ["bbc_radio_york"], directStreamUrls: nil, logoUrl: "https://sounds.files.bbci.co.uk/3.11.1/services/bbc_radio_york/blocks-colour-black_600x600.png", category: .local)
        ]
    }
    
    static func findById(_ id: String) -> WatchStation? {
        return allStations().first { $0.id == id }
    }
    
    static func favourites(from ids: [String], order: [String]) -> [WatchStation] {
        let all = allStations()
        var favs = ids.compactMap { id in all.first { $0.id == id } }
        favs.sort { a, b in
            let idxA = order.firstIndex(of: a.id) ?? Int.max
            let idxB = order.firstIndex(of: b.id) ?? Int.max
            return idxA < idxB
        }
        return favs
    }
}
